name = "vite-react-worker"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

# D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "your_database_name"
database_id = "your_database_id"

# R2 Storage Configuration
[[r2_buckets]]
binding = "R2"
bucket_name = "your_bucket_name"

# Environment Variables
[vars]
AUTH_SECRET = "your_auth_secret_here"

# Development Configuration
[dev]
port = 8787
local_protocol = "http" 